//
//  HeroChannelPresenter.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 08/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol HeroChannelPresenterInput {
    func presentSomething(response: HeroChannel.Something.Response)
}

protocol HeroChannelPresenterOutput: class {
    func displaySomething(viewModel: HeroChannel.Something.ViewModel)
}

class HeroChannelPresenter: HeroChannelPresenterInput {
    weak var output: HeroChannelPresenterOutput!

    // MARK: - Presentation logic

    func presentSomething(response: HeroChannel.Something.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller

        let channelViewModel = LiveChannelViewModel(liveChannel: response.liveChannel)
        let viewModel = HeroChannel.Something.ViewModel(liveChannelviewModel: channelViewModel)
        output.displaySomething(viewModel: viewModel)
    }
}
