//
//  HeroChannelModels.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 08/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct HeroChannel {
    struct Something {
        struct Request {
            let liveChannel: LiveChannel
        }

        struct Response {
            let liveChannel: LiveChannel
        }

        struct ViewModel {
            let liveChannelviewModel: LiveChannelViewModel
        }
    }
}
