//
//  HeroChannelConfigurator.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 08/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension HeroChannelViewController: HeroChannelPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender _: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension HeroChannelInteractor: HeroChannelViewControllerOutput {
}

extension HeroChannelPresenter: HeroChannelInteractorOutput {
}

class HeroChannelConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = HeroChannelConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: HeroChannelViewController) {
        let router = HeroChannelRouter()
        router.viewController = viewController

        let presenter = HeroChannelPresenter()
        presenter.output = viewController

        let interactor = HeroChannelInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
