//
//  HeroChannelInteractor.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 08/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol HeroChannelInteractorInput {
    func doSomething(request: HeroChannel.Something.Request)
}

protocol HeroChannelInteractorOutput {
    func presentSomething(response: HeroChannel.Something.Response)
}

class HeroChannelInteractor: HeroChannelInteractorInput {
    var output: HeroChannelInteractorOutput!
    var worker: HeroChannelWorker!

    // MARK: - Business logic

    func doSomething(request: HeroChannel.Something.Request) {
        let response = HeroChannel.Something.Response(liveChannel: request.liveChannel)
        output.presentSomething(response: response)
    }
}
