//
//  LiveChannelsPresenterTests.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 06/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import LiveTV
import XCTest

class LiveChannelsPresenterTests: XCTestCase {
    // MARK: - Subject under test

    var sut: LiveChannelsPresenter!

    // MARK: - Test lifecycle

    override func setUp() {
        super.setUp()
        setupLiveChannelsPresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: - Test setup

    func setupLiveChannelsPresenter() {
        sut = LiveChannelsPresenter()
    }

    // MARK: - Test doubles

    // MARK: - Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}
