//
//  HomeViewController.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 08/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol HomeViewControllerInput {
    //    func displaySomething(viewModel: Home.Something.ViewModel)
}

protocol HomeViewControllerOutput {
    //    func doSomething(request: Home.Something.Request)
}

class HomeViewController: UIViewController, HomeViewControllerInput {
    var output: HomeViewControllerOutput!
    var router: HomeRouter!

    var heroViewController: HeroChannelViewController!
    var liveChannelsViewController: LiveChannelsViewController!

    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        HomeConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()

        self.heroViewController = self.childViewControllers[0] as! HeroChannelViewController
        self.liveChannelsViewController = self.childViewControllers[1] as! LiveChannelsViewController

        self.liveChannelsViewController.delegate = self.heroViewController
    }

    override func prepare(for segue: UIStoryboardSegue, sender _: Any?) {
        if segue.identifier == "liveChannelsSegue" {
            let controller = segue.destination as! LiveChannelsViewController
            controller.delegate = self.heroViewController
        } else if segue.identifier == "heroSegue" {
            self.heroViewController = segue.destination as? HeroChannelViewController
        }
    }

    func displaySomething(viewModel _: Home.Something.ViewModel) {
        //
    }
}
