//
//  HomeConfigurator.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 08/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension HomeViewController: HomePresenterOutput {
}

extension HomeInteractor: HomeViewControllerOutput {
}

extension HomePresenter: HomeInteractorOutput {
}

class HomeConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = HomeConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: HomeViewController) {
        let router = HomeRouter()
        router.viewController = viewController

        let presenter = HomePresenter()
        presenter.output = viewController

        let interactor = HomeInteractor()
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
