//
//  HomeWorker.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 08/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class HomeWorker {
    // MARK: - Business Logic

    func doSomeWork() {
        // NOTE: Do the work
    }
}
