//
//  LiveChannelsViewController.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 06/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LiveChannelsViewControllerInput {
    func displaySomething(viewModel: LiveChannels.Load.ViewModel)
}

protocol LiveChannelsViewControllerOutput {
    func perform(request: LiveChannels.Load.Request)
}

class LiveChannelsViewController: UIViewController, LiveChannelsViewControllerInput {
    var output: LiveChannelsViewControllerOutput!
    var router: LiveChannelsRouter!

    // MARK: - Object lifecycle

    override func awakeFromNib() {
        super.awakeFromNib()
        LiveChannelsConfigurator.sharedInstance.configure(viewController: self)
    }

    // MARK: - View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()

        doSomethingOnLoad()
    }

    // MARK: - Event handling

    func doSomethingOnLoad() {
        // NOTE: Ask the Interactor to do some work
        let request = LiveChannels.Load.Request()
        output.perform(request: request)
    }

    // MARK: - Display logic

    func displaySomething(viewModel _: LiveChannels.Load.ViewModel) {
        // NOTE: Display the result from the Presenter

        // nameTextField.text = viewModel.name
    }
}
