//
//  LiveChannelsPresenter.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 06/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol LiveChannelsPresenterInput {
    func presentSomething(response: LiveChannels.Load.Response)
}

protocol LiveChannelsPresenterOutput: class {
    func displaySomething(viewModel: LiveChannels.Load.ViewModel)
}

class LiveChannelsPresenter: LiveChannelsPresenterInput {
    weak var output: LiveChannelsPresenterOutput!

    // MARK: - Presentation logic
    func presentSomething(response: LiveChannels.Load.Response) {
        let models: [LiveChannelViewModel] = response.liveChannelsList.flatMap({ LiveChannelViewModel(liveChannel: $0) })
        let viewModel = LiveChannels.Load.ViewModel(liveChannelsViewModels: models)
        output.displaySomething(viewModel: viewModel)
    }
}
