//
//  LiveChannelsConfigurator.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 06/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension LiveChannelsViewController: LiveChannelsPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender _: Any?) {
        router.passDataToNextScene(segue: segue)
    }
}

extension LiveChannelsInteractor: LiveChannelsViewControllerOutput {
}

extension LiveChannelsPresenter: LiveChannelsInteractorOutput {
}

class LiveChannelsConfigurator {
    // MARK: - Object lifecycle

    static let sharedInstance = LiveChannelsConfigurator()

    private init() {}

    // MARK: - Configuration

    func configure(viewController: LiveChannelsViewController) {
        let router = LiveChannelsRouter()
        router.viewController = viewController

        let presenter = LiveChannelsPresenter()
        presenter.output = viewController

        let liveChannelsService = LiveChannelsService()
        let interactor = LiveChannelsInteractor()
        interactor.inject(liveChannelsService)
        interactor.output = presenter

        viewController.output = interactor
        viewController.router = router
    }
}
