//
//  LiveChannelsModels.swift
//  LiveTV
//
//  Created by Mihai Pantiru on 06/03/2017.
//  Copyright (c) 2017 AgileFreaks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct LiveChannels {
    struct Load {
        struct Request {}

        struct Response {
            let liveChannelsList: [LiveChannel]
        }

        struct ViewModel {
            let liveChannelsViewModels: [LiveChannelViewModel]
        }
    }
}

class LiveChannelViewModel {
    let liveChannel: LiveChannel

    // MARK: - Initialization
    init(liveChannel input: LiveChannel) {
        self.liveChannel = input
    }
}

struct LiveChannel {
    let name: String
    let logoUrl: String
    let streamingUrl: String
    let title: String
}
